### ISSUE TITLE
Milestone #1: Basic in-memory download of torrent

### ISSUE THREAD

**Issue by vimpunk** [mandreyel/cratetorrent#5]
The goal is simply to exchange a handshake and process a few messages from the peer. The focus is not a full download, as saving the file is part of the next milestone.

- [x] binary message protocol
- [x] basic `PeerSession` struct that holds peer related information and peer protocol methods
- [x] perform handshake with a peer
- [x] handle other messages from peer and reply with our own messages
- [x] basic manual testing to assert that client protocol is "roughly ok"
- [x] request and receive blocks
- [x] fully download torrent into memory (without verifying it or saving to disk)
