### ISSUE TITLE
Torrent tick

### ISSUE THREAD

**Issue by mandreyel** [mandreyel/cratetorrent#65]
The periodic (1s) torrent tick needs to do the following:
- [ ] remove finished peer sessions (#64)
- [x] request more peers from tracker (#63)
- [ ] should connect peers? (#64)
- [ ] request rate limit (TBD)
- collect run times:
  - [ ] total
  - [ ] downloading
  - [ ] seeding
- [ ] send alerts to API user (#52)
- [ ] unchoke peers (#60)
- [ ] save resume data (TBD)
